#chain: config/inputs/clint-to-chm13_v1.1.chain
#vcf: config/inputs/snv_alt.bcf
#vcf: /net/eichler/vol26/projects/assembly_breaks/nobackups/asm-to-reference-alignment/results/CHM13_V1.1_v2.24_asm20/merged.vcf.gz
#vcf:  /net/eichler/vol26/projects/assembly_breaks/nobackups/asm-to-reference-alignment/human_nhp_vcf_merge/human.hap.fixed.vcf.gz
chain: config/inputs/clint_v0.15.2-to-chm13_v1.1_2022-03-14.chain
vcf: /net/eichler/vol26/projects/assembly_breaks/nobackups/asm-to-reference-alignment/human_nhp_vcf_merge/human.hap.fixed.no.chrY.vcf.gz
reference: /net/eichler/vol26/projects/chm13_t2t/nobackups/Assembly_analysis/SEDEF/chm13_v1.1_plus38Y_masked.fasta
#outgroup: /net/eichler/vol28/projects/long_read_archive/nobackups/nhp/Clint_PTR/assemblies/hifiasm/0.15.2/Clint_PTR.hifiasm.bp.hap1.p_ctg.fasta
outgroup: /net/eichler/vol26/home/mvollger/long_read_archive/nobackups/nhp/Clint_PTR/assemblies/hifiasm/0.15.2/Clint_PTR.hifiasm.bp.hap1.p_ctg.fasta
include: config/include_regions.bed
stratify:
  SD: config/annotations/SD.bed
  InterSD: config/annotations/SD_inter.bed
  IntraSD: config/annotations/SD_intra.bed
  InterAndIntraSD: config/annotations/SD_both_intra_and_inter.bed
  Unique: config/annotations/unique.bed
